- name: Configure puppetserv 
  become: yes
  template:
    src: "puppet.conf.j2"
    dest: "/etc/puppetlabs/puppet/puppet.conf"

- name: debug autosign list hosts 
  debug:
    msg: "{{ groups['slave.puppet'] }}"
- name: Add autosign list hosts     
  become: yes
  template:
    src: "autosign.conf.j2"
    dest: "/etc/puppetlabs/puppet/autosign.conf"     

