test_vm: "yes" # 256mb ram by puppetserv --default "no"
puppetserver_name: "master.puppet" # by puppet_agent on vm puppetserv 
remote_repo_by_r10k: "'https://github.com/malec0101/Master-of-puppets.git'"

disable_default: true
