version: '3'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile_jenkins
    ports:
      - "80:8080"
  nexus3:
    build:
      context: .
      dockerfile: Dockerfile_nexus
      ulimits:
        nproc: 
          soft: 5000
          hard: 15000  
    ports:
      - "81:8081"
