---
- name:  pre_provision
  hosts: all
  tasks:
  - name: disabled selinux
    become: yes
    shell: sed -i 's/^SELINUX=.*/SELINUX=disabled/g' /etc/selinux/config
  - name: 
    become: yes
    replace:
      path: /etc/ssh/sshd_config
      regexp: '^PasswordAuthentication no$'
      replace: 'PasswordAuthentication yes'
    notify:
    - Restart sshd
  - name: install packages mc, sshpass
    become: yes
    yum:
      pkg:
      - mc
      - ranger
      - tmux 
      state: present
  handlers:
  - name: Restart sshd
    become: yes
    service:
      name: sshd
      state: restarted

        # playbook puppetserver r10k install
- name: puppetserver provision
  hosts: [master.puppet]
  roles:
    - puppet_serv
    - r10k_for_puppet_serv

       # playbook puppet agent install
- name: puppet agent provision
  hosts: [slave.puppet]
  roles:
    - puppet_agent
