---
- name: a2enmod php7.4
  become: yes
  shell: a2enmod php7.4

- name: Reload Apache
  become: yes
  shell: systemctl reload apache2.service

- name: restart Apache
  service:
    name: apache2
    state: restarted    
