---
- name:  pre_provision
  hosts: all
  
  tasks:
  - name:
    become: yes  
    replace:
      path: /etc/ssh/sshd_config
      regexp: '^PasswordAuthentication no$'
      replace: 'PasswordAuthentication yes'
    notify:
    - Restart sshd

  - name: install packages mc, sshpass, tmux, ranger
    become: yes
    apt:
      pkg:
      - mc
      - sshpass
      - tmux
      - ranger
      - zsh
      - build-essential
      state: present
    register: inst_res
    
  - debug:
      msg: "{{ inst_res }}" 

        #  - name: default zsh
        #become: yes
        #shell: chsh -s $(which zsh) ; sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
        #when: inst_res == ""

  handlers:
  - name: Restart sshd
    become: yes
    service:
      name: sshd
      state: restarted

        # playbook jenkins.vm
- name: configure jenkins
  hosts: jenkins.vm
  become: true
  roles:
    - malec0101.jenkins_pipel

        # playbook nexus.vm
- name: configure nexus
  hosts: nexus.vm
  become: true
  roles:
    - malec0101.temurin.java
    - ansible-ThoTeam.nexus3-oss

        # playbook 
- name: configure staging.vm production.vm
  hosts: [environments]
  become: true
  roles:
    - malec0101.wordcloud-systd_service 
