---
- name:  pre_provision
  hosts: all
  
  tasks:
  - name: install packages mc, tmux, ranger
    become: yes
    apt:
      pkg:
      - mc
      - tmux
      - ranger
      - build-essential
      state: present

        # playbook jenkins.vm
- name: configure jenkins
  hosts: jenkins.vm
  become: true
  roles:
    - malec0101.jenkins_pipel

        # playbook nexus.vm
- name: configure nexus
  hosts: nexus.vm
  become: true
  roles:
    - malec0101.temurin.java
    - ansible-ThoTeam.nexus3-oss

        # playbook 
- name: configure staging.vm production.vm
  hosts: [environments]
  become: true
  roles:
    - malec0101.wordcloud-systd_service 
