- name: Create wordcloud directory
  become: yes
  file:
    path: /opt/wordcloud
    state: directory
    mode: '0777'

- name: Copy index test page
  template:
    src: "wordcloud.service.j2"
    dest: "/etc/systemd/system/wordcloud.service"
