---
- name: configure nexus
  hosts: localhost
  vars:
    nexus_version: '3.64.0-04'
    nexus_timezone: 'UTC'
    nexus_download_url: "https://download.sonatype.com/nexus/3"

    nexus_admin_password: 'admin'
    nexus_anonymous_access: false  # Анонимный доступ  

    nexus_min_heap_size: "600M"
    nexus_max_heap_size: "{{ nexus_min_heap_size }}"
    nexus_max_direct_memory: "2G"  

    nexus_config_maven: false  
    nexus_delete_default_repos: true 

    nexus_config_raw: true
    nexus_repos_raw_hosted:
      - name: word-cloud-build
        version_policy: mixed
        write_policy: allow  # one of "allow", "allow_once" or "deny"
        # cleanup_policies:
        #    - mvn_cleanup

    nexus_roles:
      - id: word-cloud-build # can map to a LDAP group id, also used as a key to update a role
        name: word-cloud-build
        description: All grant
        privileges:
          - nx-repository-admin-raw-word-cloud-build-*
          - nx-repository-view-raw-word-cloud-build-*

    nexus_local_users:
    - username: jenkins # used as key to update
      state: present # default value if ommited, use 'absent' to remove user
      first_name: jenkins
      last_name: CI
      email: support@company.com
      password: "jenkins"
      roles:
        - word-cloud-build # role ID
  roles:
    - ansible-ThoTeam.nexus3-oss
