- name: Create a directory r10k
  become: yes
  file:
    path: /etc/puppetlabs/r10k
    state: directory
    mode: '0751'

- name: install lib faraday 
  become: yes
  shell: /opt/puppetlabs/puppet/bin/gem install faraday -v 2.8.1
  when: chek_install_ppserv.msg == ""

- name: install lib faraday-net_http
  become: yes 
  shell: /opt/puppetlabs/puppet/bin/gem install faraday-net_http -v 3.0.2
  when: chek_install_ppserv.msg == ""
    
- name: install lib ruby "r10k"
  become: yes
  shell: /opt/puppetlabs/puppet/bin/gem install r10k -v 3.0.2
  when: chek_install_ppserv.msg == ""

- name: Add r10k.yaml
  become: yes
  template:
    src: "r10k.yaml.j2"
    dest: "/etc/puppetlabs/r10k/r10k.yaml"

- name: Add run_r10k_deploy.sh for cron
  become: yes
  template:
    src: "run_r10k_deploy.sh.j2"
    dest: "/etc/puppetlabs/r10k/run_r10k_deploy.sh"
    mode: u+x

- name: add in cron run r10k deploy
  become: yes
  cron:
    name: run r10k deploy
    minute: "*"
    job: "/etc/puppetlabs/r10k/run_r10k_deploy.sh"
   

