---
- name:  os-release
  become: yes
  shell: echo "deb https://packages.adoptium.net/artifactory/deb $(awk -F= '/^VERSION_CODENAME/{print$2}' /etc/os-release) main" | tee /etc/apt/sources.list.d/adoptium.list
  register: check_stdout

- name: Add key
  become: yes
  apt_key:
    url: https://packages.adoptium.net/artifactory/api/gpg/key/public

- name: Add repository
  become: yes
  apt_repository:
    repo: "{{ check_stdout.stdout }}"
    state: present

- name: install "{{ java_packages }}"
  become: yes
  apt:
    update_cache: true
    pkg: "{{ java_packages }}"
