- name: Create a directory r10k
  become: yes
  file:
    path: /etc/puppetlabs/r10k
    state: directory
    mode: '0751'

- name: install lib ruby "r10k"
  become: yes
  shell: /opt/puppetlabs/puppet/bin/gem install r10k
  when: chek_install_ppserv.msg == ""

- name: Add r10k.yaml
  become: yes
  template:
    src: "r10k.yaml.j2"
    dest: "/etc/puppetlabs/r10k/r10k.yaml"

