---
- name: Enable, started puppetserver
  become: yes
  systemd_service:
    name: puppetserver
    state: started
    enabled: true

- name: Restarted puppetserver
  become: yes
  systemd_service:
    name: puppetserver
    state: restarted
